# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openfruit.geography.models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_auto_20170518_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(default=openfruit.geography.models.get_united_states, on_delete=django.db.models.deletion.CASCADE, to='geography.Country'),
        ),
    ]
