# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_auto_20170823_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_private',
        ),
    ]
