# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 21:47
from __future__ import unicode_literals

from django.db import migrations
import openfruit.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_remove_location_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_hundred_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_hundredths',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_ones',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_ten_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_tens',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_tenths',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lat_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_hundred_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_hundreds',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_hundredths',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_ones',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_ten_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_tens',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_tenths',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geocoordinate',
            name='lon_thousands',
            field=openfruit.common.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
