# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('disease', '0001_initial'), ('disease', '0002_auto_20180220_0138'), ('disease', '0003_diseaseresistancereport_cultivar'), ('disease', '0004_auto_20180220_2034')]

    dependencies = [
        ('fruit_reference', '0008_auto_20180220_0138'),
        ('taxonomy', '0010_auto_20180219_1737'),
        ('fruit_reference', '0003_fruitreference_title'),
        ('fruit_reference', '0010_auto_20180220_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('disease_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseResistanceReport',
            fields=[
                ('disease_resistance_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('resistance_level', models.CharField(choices=[('p', 'Poor'), ('f', 'Fair'), ('e', 'Excellent')], max_length=1)),
                ('disease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.DiseaseType')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruit_reference.FruitReference')),
                ('cultivar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar')),
            ],
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='type',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='diseaseresistancereport',
            unique_together=set([('disease_type', 'resistance_level', 'reference', 'cultivar')]),
        ),
    ]
