# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruit_reference', '0003_fruitreference_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('disease_report_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('disease_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.DiseaseType'),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruit_reference.FruitReference'),
        ),
    ]
