# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_auto_20180219_1737'),
        ('disease', '0002_auto_20180220_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseresistancereport',
            name='cultivar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar'),
            preserve_default=False,
        ),
    ]
