# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_auto_20180219_1737'),
        ('fruit_reference', '0010_auto_20180220_2034'),
        ('disease', '0003_diseaseresistancereport_cultivar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetype',
            name='type',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='diseaseresistancereport',
            unique_together=set([('disease_type', 'resistance_level', 'reference', 'cultivar')]),
        ),
    ]
