# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:37
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openfruit.common.models
import openfruit.taxonomy.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_geo_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('cultivar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('origin_year', models.IntegerField(blank=True, null=True)),
                ('origin_exact', models.BooleanField(default=True)),
                ('color_dominate_hex', colorful.fields.RGBColorField(blank=True, null=True)),
                ('color_secondary_hex', colorful.fields.RGBColorField(blank=True, null=True)),
                ('color_tertiary_hex', colorful.fields.RGBColorField(blank=True, null=True)),
                ('featured_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='featured-images')),
                ('generated_name', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('chromosome_count', models.CharField(blank=True, choices=[('2', 'Diploid x2'), ('3', 'Triploid x3'), ('4', 'Tetraploid x4'), ('5', 'Pentaploid x5'), ('6', 'Hexaploid x6'), ('8', 'Octoploid x8')], default='2', max_length=1, null=True)),
                ('brief_description', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('origin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
                ('parent_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_children', to='taxonomy.Cultivar')),
                ('parent_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_children', to='taxonomy.Cultivar')),
            ],
            options={
                'ordering': ('generated_name',),
            },
            bases=(models.Model, openfruit.taxonomy.models.UrlNameMixin),
        ),
        migrations.CreateModel(
            name='FruitingPlant',
            fields=[
                ('fruiting_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_planted', models.DateField(default=django.utils.timezone.now)),
                ('date_died', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar')),
                ('geocoordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.GeoCoordinate')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('genus_id', models.AutoField(primary_key=True, serialize=False)),
                ('latin_name', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('featured_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='featured-images')),
                ('generated_name', models.CharField(blank=True, max_length=60, null=True, unique=True)),
            ],
            options={
                'ordering': ('generated_name',),
            },
            bases=(models.Model, openfruit.taxonomy.models.UrlNameMixin),
        ),
        migrations.CreateModel(
            name='GenusImage',
            fields=[
                ('genus_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='genus-images')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Genus')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('kingdom_id', models.AutoField(primary_key=True, serialize=False)),
                ('latin_name', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured-images')),
            ],
            options={
                'ordering': ('latin_name',),
            },
            bases=(models.Model, openfruit.taxonomy.models.UrlNameMixin),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('latin_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('can_scale_with_pruning', models.BooleanField(default=False)),
                ('years_till_full_size', openfruit.common.models.IntegerRangeField(blank=True, null=True)),
                ('full_size_height', openfruit.common.models.IntegerRangeField(blank=True, null=True)),
                ('full_size_width', openfruit.common.models.IntegerRangeField(blank=True, null=True)),
                ('years_till_first_production', openfruit.common.models.IntegerRangeField(blank=True, null=True)),
                ('years_till_full_production', openfruit.common.models.IntegerRangeField(blank=True, null=True)),
                ('featured_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='featured-images')),
                ('google_maps_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_name', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Genus')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
            ],
            options={
                'ordering': ('generated_name',),
            },
            bases=(models.Model, openfruit.taxonomy.models.UrlNameMixin),
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('species_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='species-images')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Species')),
            ],
        ),
        migrations.AddField(
            model_name='genus',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Kingdom'),
        ),
        migrations.AddField(
            model_name='fruitingplant',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Species'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together=set([('genus', 'name')]),
        ),
    ]
