# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial_squashed_0011_auto_20180228_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='brief_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
