# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitUsageType',
            fields=[
                ('cultivar_usage_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cultivar',
            name='uses',
            field=models.ManyToManyField(to='taxonomy.FruitUsageType'),
        ),
    ]
