# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20180204_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruitusagetype',
            old_name='cultivar_usage_type',
            new_name='cultivar_usage_type_id',
        ),
    ]
