# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20170518_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitingplant',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
