# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20180211_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='species',
            unique_together=set([('genus', 'latin_name')]),
        ),
    ]
