# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_auto_20180211_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='ripens_early_mod',
            field=models.CharField(choices=[('e', 'Early'), ('m', 'Mid'), ('l', 'Late')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='ripens_late_mod',
            field=models.CharField(choices=[('e', 'Early'), ('m', 'Mid'), ('l', 'Late')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='ripens_early',
            field=models.FloatField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December'), (-1, 'Unknown')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='ripens_late',
            field=models.FloatField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December'), (-1, 'Unknown')], default=-1, null=True),
        ),
    ]
