# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_auto_20170521_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitingplant',
            name='planted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
