# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_auto_20170521_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='google_maps_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
