# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_auto_20180219_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='uses',
            field=models.ManyToManyField(blank=True, null=True, to='taxonomy.FruitUsageType'),
        ),
    ]
