# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_species_google_maps_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='google_maps_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
