# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_auto_20170602_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitingplant',
            name='date_died',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruitingplant',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If the exact location of this tree should be kept private. Only you can see its location.'),
        ),
    ]
