# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_auto_20170628_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitingplant',
            name='is_private',
        ),
    ]
