# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_remove_fruitingplant_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruitingplant',
            old_name='planted',
            new_name='date_planted',
        ),
    ]
