# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_auto_20170823_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruitingplant',
            old_name='user_creator',
            new_name='created_by',
        ),
    ]
