# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openfruit.reports.event.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('event_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_auto_generated', models.BooleanField(default=False)),
                ('affinity', models.IntegerField(choices=[(-1, 'Bad'), (0, 'Neutral'), (1, 'Good')], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=openfruit.reports.event.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('passed_tense', models.CharField(help_text='The passed tense of the event word. Example: Bloomed', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='eventreport',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventType'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='fruiting_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
