# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:45
from __future__ import unicode_literals

from django.db import migrations
import openfruit.reports.event.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=openfruit.reports.event.models.upload_image),
        ),
    ]
