# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20170518_1726'),
        ('event', '0002_auto_20170510_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='cultivar',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='species',
        ),
        migrations.AddField(
            model_name='eventreport',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant'),
        ),
    ]
