# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170518_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='location',
        ),
    ]
