# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant'),
        ),
    ]
