# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170521_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreport',
            old_name='plant',
            new_name='fruiting_plant',
        ),
    ]
