# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_geo_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('new_location_lat_lon', models.CharField(blank=True, max_length=20, null=True)),
                ('new_location_name', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, help_text='If you belong to an organization such as a University, Business or Non-Profit, place it here.', max_length=50, null=True)),
                ('request_to_be_a_curator', models.BooleanField(default=False, help_text='If you would like to become a curator.')),
                ('reason_to_be_curator', models.TextField(blank=True, help_text='A brief explination of why you should be considered for becoming a curator.', null=True)),
                ('existing_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, help_text='If you belong to an organization such as a University, Business or Non-Profit, place it here.', max_length=50, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
