# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='existing_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.Location'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='new_location_lat_lon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
