# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_userlocation_user_created'),
        ('userdata', '0002_auto_20170514_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geography.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
