# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openfruit.common.models
import openfruit.taxonomy.validators


class Migration(migrations.Migration):

    replaces = [('review', '0001_initial'), ('review', '0002_auto_20180309_1517')]

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_geo_db', '0001_initial'),
        ('taxonomy', '0011_auto_20180228_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitReview',
            fields=[
                ('fruit_review_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sweet', openfruit.common.models.IntegerRangeField(default=5)),
                ('sour', openfruit.common.models.IntegerRangeField(default=5)),
                ('bitter', openfruit.common.models.IntegerRangeField(default=1)),
                ('juicy', openfruit.common.models.IntegerRangeField(default=5)),
                ('firm', openfruit.common.models.IntegerRangeField(default=5)),
                ('was_picked_early', models.BooleanField(default=False)),
                ('rating', openfruit.common.models.IntegerRangeField(blank=True, help_text='How would you personally rate this fruit?', null=True)),
                ('text', models.TextField(blank=True, help_text='Your opinion about the fruit in your own words.', max_length=1000, null=True)),
                ('was_auto_generated', models.BooleanField(default=False)),
                ('fruiting_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar')),
            ],
            bases=(models.Model, openfruit.taxonomy.validators.CultivarSpeciesMixin),
        ),
        migrations.CreateModel(
            name='FruitReviewImage',
            fields=[
                ('fruit_review_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='fruit-review-images')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
