# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openfruit.common.models
import openfruit.taxonomy.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0001_initial'),
        ('django_geo_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitReview',
            fields=[
                ('fruit_review_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sweet', openfruit.common.models.IntegerRangeField()),
                ('sour', openfruit.common.models.IntegerRangeField()),
                ('bitter', openfruit.common.models.IntegerRangeField(default=1)),
                ('juicy', openfruit.common.models.IntegerRangeField()),
                ('firm', openfruit.common.models.IntegerRangeField()),
                ('was_picked_early', models.BooleanField(default=False)),
                ('rating', openfruit.common.models.IntegerRangeField(blank=True, help_text='How would you personally rate this fruit?', null=True)),
                ('text', models.TextField(blank=True, help_text='Your opinion about the fruit in your own words.', max_length=1000, null=True)),
                ('was_auto_generated', models.BooleanField(default=False)),
                ('fruiting_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Location')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, openfruit.taxonomy.validators.CultivarSpeciesMixin),
        ),
        migrations.CreateModel(
            name='FruitReviewImage',
            fields=[
                ('fruit_review_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='fruit-review-images')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
