# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import openfruit.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_auto_20180228_1145'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitreview',
            name='location',
        ),
        migrations.AddField(
            model_name='fruitreview',
            name='cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar'),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='firm',
            field=openfruit.common.models.IntegerRangeField(default=5),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='fruiting_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.FruitingPlant'),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='juicy',
            field=openfruit.common.models.IntegerRangeField(default=5),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='sour',
            field=openfruit.common.models.IntegerRangeField(default=5),
        ),
        migrations.AlterField(
            model_name='fruitreview',
            name='sweet',
            field=openfruit.common.models.IntegerRangeField(default=5),
        ),
    ]
