# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial_squashed_0002_auto_20180309_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitreview',
            name='cultivar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.Cultivar'),
            preserve_default=False,
        ),
    ]
