# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitReference',
            fields=[
                ('fruit_reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FruitReferenceType',
            fields=[
                ('fruit_reference_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='fruitreference',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_reference.FruitReferenceType'),
        ),
    ]
