# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_auto_20180218_2200'),
        ('fruit_reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitreference',
            name='cultivar_list',
            field=models.ManyToManyField(to='taxonomy.Cultivar'),
        ),
        migrations.AddField(
            model_name='fruitreference',
            name='species_list',
            field=models.ManyToManyField(to='taxonomy.Species'),
        ),
    ]
