# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_reference', '0002_auto_20180218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitreference',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
