# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_reference', '0008_auto_20180220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitreferencetype',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
