# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_reference', '0009_auto_20180220_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fruitreferencetype',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fruitreference',
            unique_together=set([('title', 'type', 'author')]),
        ),
    ]
